---

- name: Deploy {{ photoplanet }}
  hosts: all
  sudo: yes
  sudo_user: root
#  remote_user: vagrant 
  remote_user: root 
  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/dev.yml

  roles:
    - base
    - db
    - web
#    - start

