# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

#Vagrant::Config.run do |config|
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.network :private_network, ip: "10.0.0.2"
  config.vm.provider "VUbuntu" do |vb|
    vb.customize ["modifyvm", :id, "--name", "PhotoPlanet", "--memory", "1024"]
#   vb.name = "PhotoPlanet"
#   vb.memory = 1024
#   vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
  end

  # Ansible provisioner.
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "vagrant.yml"
    ansible.host_key_checking = false
    ansible.verbose = "v"
  end
end
