---

- name: Install packages required by the Django app inside virtualenv
  pip: virtualenv={{ virtualenv_path }} requirements={{ requirements_file }}

- name: Run the Django syncdb command
  django_manage: virtualenv={{ virtualenv_path }}
                 settings={{ application_settings }}
                 command=syncdb 
                 app_path={{ application_path }}

- name: Run Django South migrations
  django_manage: virtualenv={{ virtualenv_path }}
                 settings={{ application_settings }}
                 command=migrate 
                 app_path={{ application_path }}

#- name: Run Django collectstatic
#  shell: . {{ virtualenv_path }}/bin/activate
#         && . {{ virtualenv_path }}/bin/postactivate
#         && cd {{ application_path }}
#         && python manage.py collectstatic --noinput --settings={{ django_settings_file }}
#  when: run_django_collectstatic
#  tags: django

