---

- name: Create venv dir
  command: mkdir {{ virtualenv_path }}

- name: Create the virtualenv
  command: virtualenv {{ virtualenv_path }} --no-site-packages
           creates={{ virtualenv_path }}/bin/activate

- name: Create the application log folder
  file: path={{ application_log_dir }}
        owner={{ www_user }}
        group={{ www_group }}
        mode=0774
        state=directory

- name: Create the application log file
  command: touch {{ application_log_file }}
           creates={{ application_log_file }}
         owner={{ www_user }}
         group={{ www_group }}
         mode=0774
