---

- name: Install uwsgi
  pip: name=uWSGI
  tags: packages
  sudo: yes 

- name: Create the uwsgi configuration file
  template: src=django.ini
            dest={{ uwsgi_conf }}/apps-available/django.ini
            backup=yes
            mode=644
#- name: Add the application user to the www-group
#  user: name={{ www_user }} group=www-data state=present

- name: Ensure that the application site is enabled
  command: ln -s {{ uwsgi_conf }}/apps-available/django.ini
           {{ uwsgi_conf }}/apps-enabled/django.ini
           creates={{ uwsgi_conf }}/apps-enabled/django.ini
#  notify: restart uwsgi

- name: Create the application log folder
  file: path={{ application_log_dir }}
        owner={{ www_user }}
        group={{ www_group }}
        mode=0774
        state=directory

- name: Start uwsgi
  command: sudo -u {{ www_user }} uwsgi --ini {{ uwsgi_conf }}/apps-enabled/django.ini

#- name: log file
#  command: chown www-data:www-data {{ application_log_dir }}/uwsgi.log 


